name: Run MSYS2, MinGW64-based Tests

env:
  CPPFLAGS: "-D_BSD_SOURCE"

on: [push, pull_request, workflow_dispatch]

jobs:

  build-and-test-autotools:

    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include: [
          { msystem: MINGW32 },
          { msystem: MINGW64 },
          { msystem: CLANG32 },
          { msystem: CLANG64 }
        ]
    defaults:
      run:
        shell: msys2 {0}

    steps:

      - uses: actions/checkout@v2

      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.msystem }}
          update: true
          install: zip   # for distcheck
          pacboy: autotools:p cc:p netcdf:p

###
# Configure and build
###

      - name: (Autotools) Run autoreconf
        run: autoreconf -ifv

      - name: (Autotools) Configure Build
        run: |
          mkdir bld
          cd bld
          ../configure -C
        if: ${{ success() }}

      - name: (Autotools) Look at config.log and config.cache if error
        run: |
          cat config.log
          cat config.cache
        working-directory: bld
        if: ${{ failure() }}

      - name: (Autotools) Print Summary
        run: cat ncxx4-config
        working-directory: bld

      - name: (Autotools) Build Library
        run: make V=0 -j || make V=1 -j1
        working-directory: bld
        if: ${{ success() }}

      - name: (Autotools) Build and Run Tests
        run: |
          make check -j V=0 || \
            { rc=$?; cat cxx4/test-suite.log; cat examples/test-suite.log; exit $rc; }
        working-directory: bld
        if: ${{ success() }}
        id: tests

      - name: Upload test failures
        if: ${{ failure() && steps.tests.conclusion == 'failure' }}
        uses: actions/upload-artifact@v3
        with:
          name: mingw-${{ matrix.msystem }}-autotools-test-logs
          path: bld/cxx4/*.log
                bld/cxx4/*.trs
                bld/examples/*.log
                bld/examples/*.trs

      - name: (Autotools) Run Distcheck
        run: make distcheck
        working-directory: bld
